### ISSUE TITLE
Getting some errors on ubuntu

### ISSUE THREAD

**Issue by paulo-roger** [sytone/obsidian-remote#10]
**Describe the bug**
Getting the following error when I run the command `docker-compose logs -f`
```Attaching to obsidian-remote
obsidian-remote | standard_init_linux.go:228: exec user process caused: exec format error
obsidian-remote | standard_init_linux.go:228: exec user process caused: exec format error
obsidian-remote | standard_init_linux.go:228: exec user process caused: exec format error
obsidian-remote | standard_init_linux.go:228: exec user process caused: exec format error
obsidian-remote | standard_init_linux.go:228: exec user process caused: exec format error
obsidian-remote exited with code 1
obsidian-remote | standard_init_linux.go:228: exec user process caused: exec format error
obsidian-remote | standard_init_linux.go:228: exec user process caused: exec format error
obsidian-remote | standard_init_linux.go:228: exec user process caused: exec format error
obsidian-remote | standard_init_linux.go:228: exec user process caused: exec format error
obsidian-remote | standard_init_linux.go:228: exec user process caused: exec format error
obsidian-remote | standard_init_linux.go:228: exec user process caused: exec format error
``` 

**To Reproduce**
I am running docker on a ubuntu LTS server and with the following docker-compose file:
```
version: "3.8"
services:
  obsidian:
    image: 'ghcr.io/sytone/obsidian-remote:latest'
    container_name: obsidian-remote
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /home/user/www/obsidian/vault:/vaults
      - /home/user/www/obsidian/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - DOCKER_MODS=linuxserver/mods:universal-git
```

![image](https://user-images.githubusercontent.com/103009333/164607699-4012c253-da7c-4b21-951c-03ca2770264d.png)

**Comment by paulo-roger** [comment]
After some researching I think this might be because of my ARM processor. With that in mind do you think it is possible to build a fork for ARM? I am still teaching myself about docker and so far I didn't find anything about it.

**Comment by paulo-roger** [comment]
I got it running after using this command `docker run --rm --privileged aptman/qus -s -- -p x86_64` as explained in this link: [Running x86-64 Docker Images on ARM](https://blog.techno.fish/running-x86-64-docker-images-on-arm/)

Now my problem is, Obsidian do not open in the browser window (tried both in FF and Chrome all up to date)
I only get this window:
![image](https://user-images.githubusercontent.com/103009333/164946915-a85990ed-afab-4cd8-a3a1-049c9d5b7dcd.png)
https://i.imgur.com/uxVaQCC.png

Even clicking in the Obsidian button doesn't do anything.

**Comment by erauner12** [comment]
I have this issue as well. I'm running an m1 mac. Though I never had to run `docker run --rm --privileged aptman/qus -s -- -p x86_64` to get the image up and running via docker compose. @paulo-roger did you ever get this up and going?

**Comment by erauner12** [comment]
No luck adding this either to the docker-compose file:
```
    platform: linux/amd64
```

```
version: '3.8'
services:
  obsidian:
    platform: linux/amd64
    image: 'ghcr.io/sytone/obsidian-remote:latest'
    container_name: obsidian-remote
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /Users/erauner/obsidian/vaults:/vaults
      - /Users/erauner/obsidian/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - DOCKER_MODS=linuxserver/mods:universal-git
```
