### ISSUE TITLE
Custom username/password do not work

### ISSUE THREAD

**Issue by redjax** [sytone/obsidian-remote#113]
**Describe the bug**
When running this compose stack with a `CUSTOM_USER` and `PASSWORD` environment variable fails:

```yaml
---
volumes:
  obsidian_vaults: {}
  obsidian_config: {}

services:
  obsidian:
    image: 'ghcr.io/sytone/obsidian-remote:latest'
    container_name: obsidian-remote
    restart: unless-stopped
    ports:
      - ${OBSIDIAN_HTTP_PORT:-8080}:8080
      - ${OBSIDIAN_HTTPS_PORT:-8443}:8443
    volumes:
      - ${OBSIDIAN_VAULTS_DIR:-obsidian_vaults}:/vaults
      - ${OBSIDIAN_CONFIG_DIR:-obsidian_config}:/config
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PUID:-1000}
      TZ: ${TZ:-Etc/UTC}
      DOCKER_MODS: linuxserver/mods:universal-git
      CUSTOM_PORT: 8080
      CUSTOM_HTTPS_PORT: 8443
      KEYBOARD: ${OBSIDIAN_KEYBOARD_LAYOUT:-en-us-qwerty}
      CUSTOM_USER: ${OBSIDIAN_HTTP_USER:-obsidian}
      PASSWORD: ${OBSIDIAN_HTTP_PASSWORD:-Obsidian!}
      TITLE: ${OBSIDIAN_HTTP_PAGE_TITLE:-Obsidian.md}
    healthcheck:
      test: curl -f http://localhost:8080/ || exit 1

```

Commenting/removing the `CUSTOM_USER` and `PASSWORD` values skips the VNC login screen and opens Obsidian successfully, but setting any value for the basic auth username/password causes a login window to show, and the following error message:

```text
connecting to sesman ip 127.0.0.1 port 3350
sesman connect ok
sending login info to session manager, please wait...
login failed for display 0
```

**To Reproduce**
Add `CUSTOM_USER` and `PASSWORD` environment variables to the `obsidian` service.

**Expected behavior**
The VNC authentication window should accept the values of `CUSTOM_USER` and `PASSWORD`.

**Screenshots**
With `CUSTOM_USER` and `PASSWORD` set:

![Image](https://github.com/user-attachments/assets/637dadbf-fa42-40b1-96c0-6f793a9fb4e8)

Without `CUSTOM_USER` and `PASSWORD` set:

![Image](https://github.com/user-attachments/assets/128ee814-80d5-44dc-81bd-51c6b911b6c6)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Vivaldi
- Version: latest Docker container version, Vivaldi v7.1.3570.42
