### ISSUE TITLE
Ubuntu (ARM) - openbox fails

### ISSUE THREAD

**Issue by konkalo** [sytone/obsidian-remote#42]
**Describe the bug**
I am getting an empty black screen when pointing to the container port. Starting obsidian, through right click, results into the following image. I am running this in Ubuntu 22 (aarch64/arm64).

**To Reproduce**
Fire up using this docker-compose.yml
```
version: '3.8'
services:
  obsidian:
    image: 'sytone/obsidian-remote:arm64'
    container_name: obsidian-remote
    restart: unless-stopped
    ports:
      - 7777:8080
    volumes:
      - /home/ubuntu/docker/obsidian-remote/vaults:/vaults
      - /home/ubuntu/docker/obsidian-remote/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=changed/changed
      - DOCKER_MODS=linuxserver/mods:universal-git
```

**Expected behavior**
Obsidian to run?

**Screenshots**
![Screenshot from 2023-01-12 23-54-21](https://user-images.githubusercontent.com/29521984/212198707-f2652bef-e3cf-45da-abf7-41a977f3acf9.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 20
- Browser Firefox

**Additional context**
Raspberry PI - aarch64
