### ISSUE TITLE
"exec /init: exec format error" when launching the docker container in ARM (RPI4)

### ISSUE THREAD

**Issue by Carlos672** [sytone/obsidian-remote#48]
Hi, 
Getting the exec /init: exec format error when launching docker compose in Raspberry pi 4

This is my compose:
```
version: '3.3'
services:
    obsidian-remote:
        volumes:
            - '/media/xx/vaults:/vaults'
            - '/media/xx/obsidian/config:/config'
        ports:
            - '8480:8080'
        image: 'sytone/obsidian-remote:latest'
        restart: unless-stopped
```
