### ISSUE TITLE
Support for Raspberry Pi 4

### ISSUE THREAD

**Issue by dytech-coder** [sytone/obsidian-remote#92]
Hi there,

I tried to run this container on an Raspberry Pi 4. There seems to be ARM support but not for the ARM architecture of Raspberry Pi.
Is this even possible?

**Comment by apricot13** [comment]
the arm64 version is on docker hub not github, https://hub.docker.com/r/sytone/obsidian-remote/tags `sytone/obsidian-remote:arm64` though I ran into some other issues when I ran it, but I haven't had time to look into it debugging it yet.


```
obsidian-remote  | [20240206-13:45:42] [WARN ] libscp network error.
obsidian-remote  | [20240206-13:45:42] [DEBUG] Closed socket 7 (AF_INET6 ::ffff:127.0.0.1 port 3350)
obsidian-remote  | [20240206-13:45:42] [INFO ] A connection received from ::ffff:127.0.0.1 port 39454
obsidian-remote  | [20240206-13:45:42] [WARN ] lis6-svwait: fatal: unable to subscribe to events for /var/run/s6/services/xrdp-sesman/: No such file or directory
obsidian-remote  | guacd[269]: INFO:    Guacamole connection closed during handshake
```


```yml
version: "3.8"
services:
  obsidian:
    image: sytone/obsidian-remote:arm64
    #platform: linux/arm64
    container_name: obsidian-remote
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./data/vaults:/vaults
      - ./data/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/mods:universal-git
networks: {}
```
