### ISSUE TITLE
Impossible to load the Obsidian app with local build

### ISSUE THREAD

**Issue by dogesking** [sytone/obsidian-remote#95]
**Describe the bug**
I've been building the app locally using the github repo
But when I run the container, and go to the web interface, when I click Obsidian I get the error : 
`Failed to execute child process "/squashfs-root/obsidian" (No such file or directory)`

**To Reproduce**
clone the repo
```
docker build --pull --rm `
  -f "Dockerfile" `
  -t obsidian-remote:latest `
  "."
```
```
docker run --rm -it `
  -v D:/ob/vaults:/vaults `
  -v D:/ob/config:/config `
  -p 8080:8080 `
  obsidian-remote:latest bash
```
Go to the url poiting to the container
Click on Obsidian and get the error : `Failed to execute child process "/squashfs-root/obsidian" (No such file or directory)`

**Expected behavior**
Be able to use the Obsidian app after clicking

**Screenshots**
![image](https://github.com/sytone/obsidian-remote/assets/115567119/7531c850-0c2d-4dde-afc9-28ea2dd06589)

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser [Chrome]

**Comment by xX-MrN0b0dy-Xx** [comment]
I use WSL and compose and when I want to build locally I do:
```yml
    # image: sytone/obsidian-remote:latest
    build:
      context: /projects/docker/obsidian-remote-fork/
      dockerfile: Dockerfile #change if on arm
    image: obsidian-remote:local-build
```

But there is a problem in the repo currently and it won't work. I fixed it locally though. When I have time I'll create an issue and raise a PR that fix it. Probably it will fix also this problem, even if I never encountered it...
